language: php

php:
    - 7.0

notifications:
    slack: mti2018:0seGiAUl4SB3agRocEnT7qoe
    on_failure: always
    on_success: always

before_script:
    - chmod 777 -R storage
    - cp .env.travis .env
    - mysql -e 'create database blind_db;'
    - mysql -u root --default-character-set=utf8 blind_db < bdd/blind_db.sql
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate

script:
    - vendor/bin/phpunit
