language: php

php:
    - 7.0

notification:
    slack: mti2018:0seGiAUl4SB3agRocEnT7qoe

before_script:
    - chmod 777 -R storage
    - cp .env.travis .env
    - mysql -e 'create database blind_db;'
    - composer self-update
    - composer install --no-interaction
    - php artisan key:generate

script:
    - vendor/bin/phpunit
